# Generated by Django 6.0.2 on 2026-04-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carselling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='seller',
        ),
    ]
