# Generated by Django 6.0.2 on 2026-04-25 12:10

import carselling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carselling', '0002_remove_car_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=carselling.models.getfilename),
        ),
    ]
