# Generated by Django 6.0.2 on 2026-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carselling', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-show, 1-Hidden'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
