# Generated by Django 6.0.2 on 2026-04-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carselling', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
